[manager]
prepend_keymap = [
    { on = "<C-j>", run = "arrow 5", desc = "Move down 5 lines" },
    { on = "<C-k>", run = "arrow -5", desc = "Move up 5 lines" },
    { on = "<Esc>", run = "unyank", desc = "Unyank file" },
    { on = "y", run = [
        '''
        shell 'xclip -selection clipboard -t image/png -i "$@"' --confirm
        ''',
        "yank"
    ], desc = "Yank image and copy it to clipboard" }
]

