[manager]
cwd = { fg = "white"}
preview_hovered = { bg = "#32302f", fg = "#458588" }
hovered = { bg = "#32302f", fg = "#458588"}
border_style = { fg = "#32302f"}

[mode]
normal_main = { fg = "white", bg = "#458588", bold = true }
normal_alt  = { fg = "#458588", bg = "#32302f"}

select_main = { fg = "white", bg = "#458588", bold = true }
select_alt  = { fg = "#282828", bg = "#32302f"}

unset_main = { fg = "white", bg = "#458588", bold = true }
unset_alt  = { fg = "#458588", bg = "#32302f"}

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "black", bg = "#32302f" }

# Progress
progress_label  = { fg = "white", bold = true }
progress_normal = { fg = "black", bg = "gray" }
progress_error  = { fg = "red", bg = "gray" }

# Permissions
permissions_t = { fg = "white" }
permissions_r = { fg = "green" }
permissions_w = { fg = "red" }
permissions_x = { fg = "green" }
permissions_s = { fg = "white" }

[filetype]
rules = [
    # Fallback
    { name = "*", fg = "white" },
    { name = "*/", fg = "#458588" }
]
