[manager]
cwd = { fg = "white"}
preview_hovered = { fg = "black", bg = "blue" }
hovered = { fg = "black", bg = "blue"}
border_style = { fg = "#32302f"}

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "black", bg = "#32302f" }
# Mode
mode_normal = { fg = "white", bg = "#458588", bold = true }
mode_select = { fg = "white", bg = "green", bold = true }
mode_unset  = { fg = "white", bg = "magenta", bold = true }

# Progress
progress_label  = { fg = "white", bold = true }
progress_normal = { fg = "black", bg = "gray" }
progress_error  = { fg = "red", bg = "gray" }

# Permissions
permissions_t = { fg = "white" }
permissions_r = { fg = "green" }
permissions_w = { fg = "red" }
permissions_x = { fg = "green" }
permissions_s = { fg = "white" }

[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "blue" },

    # Videos
    { mime = "video/*", fg = "lightgreen" },
    { mime = "audio/*", fg = "lightgreen" },

    # Archives
    { mime = "application/zip",             fg = "lightred" },
    { mime = "application/gzip",            fg = "lightred" },
    { mime = "application/x-tar",           fg = "lightred" },
    { mime = "application/x-bzip",          fg = "lightred" },
    { mime = "application/x-bzip2",         fg = "lightred" },
    { mime = "application/x-7z-compressed", fg = "lightred" },
    { mime = "application/x-rar",           fg = "lightred" },

    # Fallback
    { name = "*", fg = "white" },
    { name = "*/", fg = "blue" }
]

