set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g prefix C-a
unbind C-b
bind-key C-a send prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

# kill window
bind q killp

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

set -g @plugin 'tmux-plugins/tmp'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'gordonn/tmux'
set -g @catppuccin_status_modules_right "null"
set-option -g status-position top
set -g @catppuccin_status_background "default"

run '~/.tmux/plugins/tpm/tpm'
